
INSERT INTO notas (titulo, msj_nota, create_at) VALUES('Titulo de prueba', 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', NOW());
INSERT INTO notas (msj_nota, titulo, create_at) VALUES('En este artículo encontrarás todo lo necesario para crear tu carta de recomendación. Ejemplos para copiar y pegar, una carta para descargar en Word y una herramienta para crear tu carta de recomendación personalizada. A continuación te presento modelos de carta de recomendación, carta de recomendación personal y carta de recomendación laboral para copiar y pegar. Modifícales a tu antojo, son de uso libre. Si buscas un ejemplo en Word, da clic para descargarlo.', 'Ejemplo de Carta De Recomendación',  NOW());
INSERT INTO notas (msj_nota, titulo, create_at) VALUES('Por medio de la presente se le informa a todo el personal que con motivo del acuerdo establecido entre esta empresa y el Deportivo No. 22 "Jesús Chávez Piñeiro", a partir del próximo 12 de julio del año en curso todos los empleados podrán hacer uso de las instalaciones de dicho deportivo pagando una cuota mínima de $100.00 mensuales. Este pago le da derecho al trabajador a utilizar todas las instalaciones deportivas sin ninguna restricción. Asimismo, le permite obtener descuentos en la memebresía de familiares. Los empleados interesados en este beneficio deberán de presentarse los días 6, 7, 8 y 9 de julio del año en curso en las oficinas de recursos humanos para realizar su registro y el trámite correspondiente. Después de ello recibirán su credencial que los avala como socios del deportivo. Sin más por el momento, esperamos contar con su participación. esta empresa sin duda cree y promueve el deporte.', 'Ejemplo de nota administrativa',  NOW());


INSERT INTO comentarios (msj_comentario, nota_id, create_at) VALUES('Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 1,  NOW());
INSERT INTO comentarios (msj_comentario, nota_id, create_at) VALUES(' dolor sit amet consectetur adipisicing elit. Atque et nostrum reiciendis nemo nihil neque, est facilis, aut vitaeLorem ipsum dolor sit amet. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 1,  NOW());
INSERT INTO comentarios (msj_comentario, nota_id, create_at) VALUES('Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 2,  NOW());
INSERT INTO comentarios (msj_comentario, nota_id, create_at) VALUES(' dolor sit amet consectetur adipisicing elit. Atque et nostrum reiciendis nemo nihil neque, est facilis, aut vitaeLorem ipsum dolor sit amet. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 2,  NOW());
INSERT INTO comentarios (msj_comentario, nota_id, create_at) VALUES('Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 3,  NOW());
INSERT INTO comentarios (msj_comentario, nota_id, create_at) VALUES(' dolor sit amet consectetur adipisicing elit. Atque et nostrum reiciendis nemo nihil neque, est facilis, aut vitaeLorem ipsum dolor sit amet. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 3,  NOW());


INSERT INTO respuestas (msj_respuesta, respuesta_id, create_at) VALUES('Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!Lorem asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 1,  NOW());
INSERT INTO respuestas (msj_respuesta, respuesta_id, create_at) VALUES(' Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!Lorem asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 2,  NOW());
INSERT INTO respuestas (msj_respuesta, respuesta_id, create_at) VALUES('Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis minima in dicta error temporibus, excepturi, rem fugiat expedita ut asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!Lorem asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 3,  NOW());
INSERT INTO respuestas (msj_respuesta, respuesta_id, create_at) VALUES(' dolor sit amet consectetur adipisicing elit. Atque et nostrum reiciendis nemo nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 4,  NOW());
INSERT INTO respuestas (msj_respuesta, respuesta_id, create_at) VALUES('Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae blanditiis asperiores nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 5,  NOW());
INSERT INTO respuestas (msj_respuesta, respuesta_id, create_at) VALUES(' dolor sit amet consectetur adipisicing elit. Atque et nostrum reiciendis nemo nemo, optio quibusdam voluptas aliquid amet. Tenetur, soluta. At!', 6,  NOW());



/* Creamos algunos usuarios con sus roles */
INSERT INTO `usuarios` (username, password, enabled, nombre, apellido, email) VALUES ('andres','$2a$10$C3Uln5uqnzx/GswADURJGOIdBqYrly9731fnwKDaUdBkt/M3qvtLq',1, 'Andres', 'Guzman','profesor@bolsadeideas.com');
INSERT INTO `usuarios` (username, password, enabled, nombre, apellido, email) VALUES ('admin','$2a$10$RmdEsvEfhI7Rcm9f/uZXPebZVCcPC7ZXZwV51efAvMAp1rIaRAfPK',1, 'John', 'Doe','jhon.doe@bolsadeideas.com');

INSERT INTO `roles` (nombre) VALUES ('ROLE_USER');
INSERT INTO `roles` (nombre) VALUES ('ROLE_ADMIN');

INSERT INTO `usuarios_roles` (usuario_id, role_id) VALUES (1, 1);
INSERT INTO `usuarios_roles` (usuario_id, role_id) VALUES (2, 2);
INSERT INTO `usuarios_roles` (usuario_id, role_id) VALUES (2, 1);
